### ISSUE TITLE
Rework Pagination / use a url package, walk links

### ISSUE THREAD

**Issue by derwolfe** [RackSec/cloudpassage-lib#13]
Instead of creating pagination links in advance, we should walk the links returned by the api. This is more robust in the case that our clock is out of sync with cloudpassage's.

This will likely require
1. parsing the url returned by the next link, and turning it into a request
2. pushing the resulting request map onto the input-stream
3. Reworking the tests.

Also, this looks like it would be a good place to clean up how urls and request data are being sent to the actual page fetcher. Instead of creating a string representing the complete uri in advance, Aleph has support for query parameters. fetch-events! currently builds this string manually.

(original issue here https://github.com/RackSec/cloudpassage-poller/issues/45#issuecomment-195562946)

**Comment by derwolfe** [comment]
Closing as this doesn't really seem relevant to the library. It was mainly intended for the event fetching logic, all of which lives elsewhere.

**Comment by ehashman** [comment]
Thanks for closing this up, @derwolfe!
