### ISSUE TITLE
Off by one error when calling scans!

### ISSUE THREAD

**Issue by derwolfe** [RackSec/cloudpassage-lib#31]
Calling the `sca` api is (likely) returning one too few page of results. 

The reason for this behavior is (here)[https://github.com/RackSec/cloudpassage-lib/blob/4c67340c1224c90789deb8b7a7af1854e7bcdf82/src/cloudpassage_lib/scans.clj#L81]. The call to `ms/put-all ...` might be called on a stream that has already been closed. The solution would be to move the call to `ms/put-all` above the conditional branch that closes the streams, as shown [here](https://github.com/RackSec/cloudpassage-lib/pull/24/files)

**Comment by ehashman** [comment]
Closed by #33.
