### ISSUE TITLE
Add docs for the clojars release process

### ISSUE THREAD

**Issue by ehashman** [RackSec/cloudpassage-lib#9]
- How to sign up for clojars and deal with credentials
- Adding someone to the group so they can upload releases
- How to cut a release and push changes back to master using `lein release`

**Comment by derwolfe** [comment]
To do a release, you must have a file `~/.lein/credentials.clj.gpg` that contains your gpg encrypted clojars account credentials. To perform the actual release, cd into the root `cloudpassage-lib` directory, make sure you are have the most recently merged master and hit `lein release :minor`. This will generate a minor version release, bump the version, and create a tag. Then push this tag and version change to master.
